### ISSUE TITLE
Mining sheet broken

### ISSUE THREAD

**Issue by Zenthae** [deniszholob/factorio-cheat-sheet#311] opened 2021-05-05 03:15 UTC
no title displayed and can't collapse the mining cheat sheet

![image](https://user-images.githubusercontent.com/32647899/117093276-c647ec00-ad60-11eb-94fa-c910c2a36e1b.png)

**Comment by deniszholob** [comment] 2021-05-19 13:38
Cannot reproduce.
I would try seeing if any browser extensions are messing up the loading of data, others have reported bugs that were solved by disabling certain extensions.

**Comment by navaati** [comment] 2021-06-05 13:04
Hi.

Here is the error objet on Firefox:
```json
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null,
    "headers": {}
  },
  "status": 0,
  "statusText": "Unknown Error",
  "url": "https://factoriocheatsheet.com/assets/data/mining.json",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://factoriocheatsheet.com/assets/data/mining.json: 0 Unknown Error",
  "error": {
    "isTrusted": true
  }
}
```
and on Chromium:
```json
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null,
        "headers": {}
    },
    "status": 0,
    "statusText": "Unknown Error",
    "url": "./assets/data/mining.json",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for ./assets/data/mining.json: 0 Unknown Error",
    "error": {
        "isTrusted": true
    }
}
```

To add to what the OP said about the problem, another symptom is that the symptoms clicking on the "Mining" link in the menu at the right of the screen doesn’t work and produces an additional error in the console.

**Comment by navaati** [comment] 2021-06-05 13:11
Ok, actually I found out the culprit: it was indeed the extension "Ublock Origin", see this excerpt of the request log from the extension:
![image](https://user-images.githubusercontent.com/1193282/120892667-b6495380-c60f-11eb-9337-42677e0cde92.png)

It appears the extension is triggering on the `mining.js` part of the url, so the bug is indeed with the extension (or rather the blocklist used by default). On my side I added a specific allow for your domain name and now things work fine.

Long term solution would be to submit a fix to the blocklist so that the rule is `/mining.js$` instead of `mining.js`, but… I have no idea on how to do that.

It’s a bit dumb, and not your fault, but as Ublock Origin is a very popular extension, as a workaround you may want to rename the file to `/resource_mining.json` or something like that, if that’s possible…

**Comment by deniszholob** [comment] 2021-06-05 21:08
@navaati Thanks for the details, i got rid of the json stuff now, it should just have data. Can you check again, should be loading fine without the rule now i think.

**Comment by Zenthae** [comment] 2021-06-05 22:31
issue fixed for me, thanks !

**Comment by deniszholob** [comment] 2021-06-06 00:37
Sweet ill close the issue, feel free to reopen if it comes up again, but there might not be much else i can do if its caused by extensions.

**Closed by deniszholob** 2021-06-06 00:37 UTC
Labels: In Discussion, bug

**Comment by navaati** [comment] 2021-06-06 09:42
Yup, can confirm as well ! Wow, that was a big patch in such a short amount of time.

Thank you !
